image: drud/ddev-gitpod-base:20221018

tasks:
  - name: ddev-gitpod-launcher
    before: |
      if [ $GITPOD_IDE_ALIAS = "phpstorm" ]; then echo -e 'alias npm="ddev exec npm " \n alias php="ddev exec php"  ' >> ~/.bashrc  ;fi
      apt-get update
      apt-get install -y ddev
      ddev start -y
      export DDEV_NONINTERACTIVE=true
      ddev exec "cat .env.example | sed  -E 's/DB_(HOST|DATABASE|USERNAME|PASSWORD)=(.*)/DB_\1=db/g' > .env"
      ddev exec 'sed -i "s#APP_URL=.*#APP_URL=${DDEV_PRIMARY_URL}#g" .env'
      ddev exec "php artisan key:generate"
      ddev exec "php artisan migrate"
      ddev exec "php artisan db:seed"
      ddev exec "php artisan storage:link"
    init: |
      ddev composer install
      ddev npm i -g npm@latest
      ddev npm install
      ddev npm audit fix --force

      ddev npm run dev
    command: |

      ddev launch

vscode:
  extensions:
    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

jetbrains:
  phpstorm:
    prebuilds:
      version: stable
    plugins:
      - ru.adelf.idea.dotenv
      - de.docs_as_co.intellij.plugin.diagramsnet
      - com.github.googee.laravelgenerator
      - com.laravel_idea.plugin
      - com.github.lppedd.idea-conventional-commit
      - de.docs_as_co.intellij.plugin.diagramsnet



github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

ports:
  # Ignore direct-build https port
  - port: 2222
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
  # Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
  # router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
  # router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
  # xdebug port
  - port: 9000
    onOpen: ignore
  # projector port
  - port: 9999
